A = {1, 2, 3, 4, 5}
B = {4, 5, 6, 7, 8}
union_AB = A.union(B)
print("I. Join A and B (Union):", union_AB)
intersection_AB = A.intersection(B)
print("II. Intersection of A and B:", intersection_AB)
is_A_subset_B = A.issubset(B)
print("III. Is A a subset of B?", is_A_subset_B)
are_disjoint = A.isdisjoint(B)
print("IV. Are A and B disjoint sets?", are_disjoint)
join_A_with_B = A.union(B)
print("V. Join A with B:", join_A_with_B)
join_B_with_A = B.union(A)
print("V. Join B with A:", join_B_with_A)
symmetric_difference_AB = A.symmetric_difference(B)
print("VI. Symmetric difference between A and B:", symmetric_difference_AB)
A.clear()
B.clear()
print("VII. Sets after deletion, A:", A, "B:", B)
